# Generated by Django 4.1.7 on 2023-03-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=150)),
                ('shipping_type', models.BooleanField()),
                ('shipping_price', models.BooleanField()),
                ('description_products', models.TextField()),
                ('product_city', models.CharField(max_length=30)),
                ('image_product', models.ImageField(default='null', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
