# Generated by Django 4.1.7 on 2023-03-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='product_price',
            field=models.FloatField(default='null'),
        ),
    ]
