# Generated by Django 4.1.7 on 2023-03-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0003_alter_article_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product_price',
            field=models.FloatField(default='1.00'),
        ),
    ]
