# Generated by Django 4.1.7 on 2023-03-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0009_article_product_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='product_prices',
        ),
    ]
