# Generated by Django 4.1.7 on 2023-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0010_remove_article_product_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
