# Generated by Django 4.2 on 2023-05-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0013_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='min_image_one',
            field=models.ImageField(default='null', upload_to='image_products_min'),
        ),
        migrations.AddField(
            model_name='article',
            name='min_image_two',
            field=models.ImageField(default='null', upload_to='image_products_min'),
        ),
    ]
