# Generated by Django 4.2 on 2023-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0014_article_min_image_one_article_min_image_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='none', max_length=150, verbose_name='URL FRIENDLY :D'),
        ),
    ]
