# Generated by Django 4.2 on 2023-05-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0015_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='none', max_length=150, unique=True, verbose_name='URL FRIENDLY :D'),
        ),
    ]
